/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import chat.Message;
import java.awt.Color;

/**
 *
 * @author dvcarrillo
 */
public class MessageView extends javax.swing.JPanel {
    
    private Color messageColor;
    private Message message;
    
    /**
     * SET method for the message
     */
    public void SetMessage(Color color, Message msg) {
        messageColor = color;
        messageText.append(msg.getUsername() + ":\n" + msg.getText());
                
    }

    /**
     * Creates new form MessageView
     */
    public MessageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messageText = new javax.swing.JTextArea();
        messageTime = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));

        messageText.setEditable(false);
        messageText.setBackground(new java.awt.Color(42, 102, 254));
        messageText.setColumns(20);
        messageText.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        messageText.setForeground(new java.awt.Color(254, 254, 254));
        messageText.setLineWrap(true);
        messageText.setRows(5);
        messageText.setText("David:\nHola primo aajajajjajjajjjajj j ajj aj ajjidiaj ij iajia jia jij aij aijdij aij idjd iaj ");
        messageText.setWrapStyleWord(true);
        messageText.setAutoscrolls(false);
        messageText.setFocusable(false);
        messageText.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(messageText);

        messageTime.setForeground(new java.awt.Color(123, 123, 123));
        messageTime.setText("10:10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(messageTime)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addComponent(messageTime))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageText;
    private javax.swing.JLabel messageTime;
    // End of variables declaration//GEN-END:variables
}
